version: "3"

services:
  server:
    image: "vuttr-node"
    container_name: NODEJS_SERVER_MEDIUM
    build: '.'
    command: "yarn start"
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes: 
       - "./api:/usr/app/api"

  db:
    image: "mongo"
    container_name: MONGODB_MEDIUM
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"